load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary (
    name = "ls",
    srcs = ["ls.c"],
    visibility = ["//visibility:public"],
)

cc_binary (
    name = "sh",
    srcs = ["sh.cc"],
    visibility = ["//visibility:public"],
)

cc_binary (
    name = "r_w_seek",
    srcs = ["r_w_seek.cc"],
    visibility = ["//visibility:public"],
)